### ISSUE TITLE
Linux64 Delphi compilation error (10..3.1)

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#577]
I tried this under 10.3.0 and had the same problem but thought I'd re-test under 10.3.1 as with that version FMXLinux comes from GetIt rather than using the trial

CastleClassUtils.pas Line 1221
  if backEndingChar then Stream.Seek(-1, soFromCurrent);

[DCC Error] castleclassutils.pas(1221): E2251 Ambiguous overloaded call to 'Seek'
  System.Classes.pas(983): Related method: function TStream.Seek(LongInt; Word): LongInt;
  System.Classes.pas(985): Related method: function TStream.Seek(const Int64; Word): Int64;

Got this while trying to compile test project in 10.3.0 and whilst trying to build library for Linux64 (doinmg complete test) under 10.3.1

Note that while FMXLinux is installale there is a DLL error on load regarding not being able to find an entry point but this is a FMXLinux issue so prob un-related

As 10.2.x failed to install FMXLinux trial I've also written to the authors (and pointed them at your FMXLinux stuff etc)

**Comment by peardox** [comment]
10.3.1 had FMXLinux via GetIt
10.4.2 - Bad GetIt even after a GetItCmd.exe -c=useonline so have to use trial again

Gets further in build in 10.4.2 but link error
[DCC Error] E2597 C:\Program Files (x86)\Embarcadero\Studio\21.0\bin\ld-linux.exe: error: cannot open C:\\Users\\simon\\OneDrive\\Documents\\Embarcadero\\Studio\\SDKs\\ubuntu22.04.sdk/lib64/ld-linux-x86-64.so.2: No such file or directory 
Note the suspicious path... How annoying (there's no lib64 - it's in lib/x86_64-linux-gnu) so after hacking that

To replicate this issue grab the 10.3.1 ISO from my.embarcadero.com and install FMXLinux via GetIt then try building the Linux64 app

Oh on FMXLinux instructions you say....
> You also need to provide the username and password to connect to the PA Server running on it.

You don't actually need a user name

End result....

![image](https://github.com/castle-engine/castle-engine/assets/1549219/283b810c-631e-4ced-ab9f-e697770dff74)

**Comment by michaliskambi** [comment]
> You also need to provide the username and password to connect to the PA Server running on it.

Thanks, corrected, no username :)

As for the core of this: Thank you, let it wait until I regain access to Delphi 10.x which I essentially lost last week (i used my DevRel key one time too many :) ). Waiting for Ian's answer.

**Comment by peardox** [comment]
He knows this kinda thing happens - had my limit doubled on DevRel

A trick I found was to.... [Instructions make this sound a bigger job than it is]

Create a base clean Windows VM. 
Stick Git, Notepad++ and any other useful bits on it.
Mount any of the DevRel ISOs and start a the setup
Register with your DevRel key
When the actual RadStudio Installer comes up CANCEL
Uninstall RadStudio (it throws a bit in there before any langugaes get near the VM)
Delete Embarcadero directories in Program Files (x86), Documents and Public Documents
Delete the ISO you started installing from
Tidy up (empty Recycle Bin etc)
Turn off VM

Compact / Defrag the VM's HD
Zip/Rar the VM so you have your baseline clean machine with no Delphi (but a key still exists)

Start VM
Install Delphi and play as much as you like

Later....
Delete VM
Restore backup
Repeat (a new version of Delphi or whatever)

**_This bypasses the installatiuuon counter_**

You've now got the ability to use yer DevRel with impunity (or until they change how licensing works)

**Comment by peardox** [comment]
Oh, yeah. Same story but without a DevRel key

This is how I'm testing CE versions now except the clean is one stage earlier. Then use that to install Delphi CE and backup then repezt with CBuilder CE

End result is 
1 ) Windows+Delphi CE VM
2 ) Windows+CBuilder CE VM
3 ) Windows+DevRel waiting to be installed VM

**Comment by michaliskambi** [comment]
I've tested Delphi / Linux on Delphi 10.2.3. 

After 

> lib64/ld-linux-x86-64.so.2: No such file or directory

...I ran into more incompatibilities, `AnsiString` and `AnsiChar` don't exist and it's unclear how to even declare them:

```delphi
program Project1;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils;
{$H-}
{$if not declared(AnsiString)}
type
  AnsiString = String; // needed on Linux in Delphi 10.2.3
{$endif}
{$if not declared(AnsiChar)}
type
  AnsiChar = Char; // needed on Linux in Delphi 10.2.3
{$endif}
{$H+}
var
  A: AnsiString;
begin
  A := 'foo';
  Writeln(A);
  Writeln(SizeOf(A[1]));
    // 1 on Windows in Delphi 10.2.3, as it should -- this is AnsiString
    // 2 on Linux in Delphi 10.2.3 (so despite $H, String was UnicodeString)
  Readln;
end.
```

So I did yet get to the issue

> [DCC Error] castleclassutils.pas(1221): E2251 Ambiguous overloaded call to 'Seek'

you reported at the begging of this with 10.3.0 .

I say to officially say we don't support Linux with these older Delphis. It doesn't seem feasible to apply hack over hack -- it would be too easy to break (when everyone in practice works on newer FPC and Delphi versions) and the benefit for users is slim. Until we hear more reports from Delphi people with older Delphi versions. I'll update  https://castle-engine.io/delphi to make our support clear.
